//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace floridapp {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Español {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Español() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("floridapp.Español", typeof(Español).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca.
        /// </summary>
        internal static string btnBiblioteca {
            get {
                return ResourceManager.GetString("btnBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cafeteria.
        /// </summary>
        internal static string btnCafeteria {
            get {
                return ResourceManager.GetString("btnCafeteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Pedido.
        /// </summary>
        internal static string btnLimpiarPedido {
            get {
                return ResourceManager.GetString("btnLimpiarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Grados.
        /// </summary>
        internal static string btnListaMod {
            get {
                return ResourceManager.GetString("btnListaMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza Tu Reserva .
        /// </summary>
        internal static string btnReservaPortatil {
            get {
                return ResourceManager.GetString("btnReservaPortatil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunion.
        /// </summary>
        internal static string btnReunion {
            get {
                return ResourceManager.GetString("btnReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida.
        /// </summary>
        internal static string button5 {
            get {
                return ResourceManager.GetString("button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para Llevar.
        /// </summary>
        internal static string cbLlevar {
            get {
                return ResourceManager.GetString("cbLlevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva:.
        /// </summary>
        internal static string lblHora {
            get {
                return ResourceManager.GetString("lblHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string lblInicio {
            get {
                return ResourceManager.GetString("lblInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu:.
        /// </summary>
        internal static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesa:.
        /// </summary>
        internal static string lblMesa {
            get {
                return ResourceManager.GetString("lblMesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nunca es mal momento para comer.
        /// </summary>
        internal static string lblNunca {
            get {
                return ResourceManager.GetString("lblNunca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecio {
            get {
                return ResourceManager.GetString("lblPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Proceder al trámite e imprimir factura.
        /// </summary>
        internal static string lblProceder {
            get {
                return ResourceManager.GetString("lblProceder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza tu Pedido.
        /// </summary>
        internal static string lblRealizaPe {
            get {
                return ResourceManager.GetString("lblRealizaPe", resourceCulture);
            }
        }
    }
}
