//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace floridapp.RecursoL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("floridapp.RecursoL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscas un portatil?.
        /// </summary>
        internal static string bib1 {
            get {
                return ResourceManager.GetString("bib1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de reserva de salas y portatiles.
        /// </summary>
        internal static string bib2 {
            get {
                return ResourceManager.GetString("bib2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al espacio de biblioteca,
        ///en este apartado tendrás la posibilidad
        ///de reservar los equipos informáticos que 
        ///provee el centro educativo, también tendrás
        ///que concretar las horas de uso de este mismo
        ///para que una vez finalizado el tiempo de uso
        ///esté pueda ser devuelto a la biblioteca del centro..
        /// </summary>
        internal static string bib3 {
            get {
                return ResourceManager.GetString("bib3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Reserva.
        /// </summary>
        internal static string bib4 {
            get {
                return ResourceManager.GetString("bib4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por solamente:.
        /// </summary>
        internal static string caf1 {
            get {
                return ResourceManager.GetString("caf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Paella.
        /// </summary>
        internal static string caf2 {
            get {
                return ResourceManager.GetString("caf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paella tradicional valenciana.
        /// </summary>
        internal static string caf3 {
            get {
                return ResourceManager.GetString("caf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al espacio de cafetería, aquí 
        ///tendrás la oportunidad de tanto realizar 
        ///pedidos como reservar mesas en la cafetería de 
        ///nuestra institución, dispondrás de la opción de 
        ///poder llevarte tu pedido para llevar. En el momento 
        ///en el cual realices tu pedido se te enviara una 
        ///factura a tu correo la cual posteriormente tendrás 
        ///que mostrar en la cafetería para poder pagarlo..
        /// </summary>
        internal static string caf4 {
            get {
                return ResourceManager.GetString("caf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Pedido.
        /// </summary>
        internal static string caf5 {
            get {
                return ResourceManager.GetString("caf5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca.
        /// </summary>
        internal static string f1bib {
            get {
                return ResourceManager.GetString("f1bib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cafeteria.
        /// </summary>
        internal static string f1caf {
            get {
                return ResourceManager.GetString("f1caf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string f1ini {
            get {
                return ResourceManager.GetString("f1ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista grados.
        /// </summary>
        internal static string f1list {
            get {
                return ResourceManager.GetString("f1list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión.
        /// </summary>
        internal static string f1reu {
            get {
                return ResourceManager.GetString("f1reu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string f1sal {
            get {
                return ResourceManager.GetString("f1sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar ciclos.
        /// </summary>
        internal static string la1 {
            get {
                return ResourceManager.GetString("la1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta la información de tus alumnos.
        /// </summary>
        internal static string la2 {
            get {
                return ResourceManager.GetString("la2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un modulo.
        /// </summary>
        internal static string la3 {
            get {
                return ResourceManager.GetString("la3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string la4 {
            get {
                return ResourceManager.GetString("la4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar ciclos.
        /// </summary>
        internal static string lm1 {
            get {
                return ResourceManager.GetString("lm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta la información de tus profesores.
        /// </summary>
        internal static string lm2 {
            get {
                return ResourceManager.GetString("lm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona ciclo.
        /// </summary>
        internal static string lm3 {
            get {
                return ResourceManager.GetString("lm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string lm4 {
            get {
                return ResourceManager.GetString("lm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string locon {
            get {
                return ResourceManager.GetString("locon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string locor {
            get {
                return ResourceManager.GetString("locor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string loent {
            get {
                return ResourceManager.GetString("loent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string losal {
            get {
                return ResourceManager.GetString("losal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Florida News.
        /// </summary>
        internal static string new1 {
            get {
                return ResourceManager.GetString("new1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras noticias más recientes.
        /// </summary>
        internal static string new2 {
            get {
                return ResourceManager.GetString("new2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More.
        /// </summary>
        internal static string new3 {
            get {
                return ResourceManager.GetString("new3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organizar una reunión.
        /// </summary>
        internal static string reu1 {
            get {
                return ResourceManager.GetString("reu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con tus profesores de confianza.
        /// </summary>
        internal static string reu2 {
            get {
                return ResourceManager.GetString("reu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al espacio de reuniones,
        ///en este apartado tendrás la posibilidad
        ///de organizar reuniones con todos y cada
        ///uno de los docentes de tu ciclo, tendras
        ///la opción de concretar la hora del encuentro
        ///para resolver cada una de tus dudas, también 
        ///te será confirmada la reunión con un correo que 
        ///te llegara a tu bandeja de entrada..
        /// </summary>
        internal static string reu3 {
            get {
                return ResourceManager.GetString("reu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza la tuya propia.
        /// </summary>
        internal static string reu4 {
            get {
                return ResourceManager.GetString("reu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza tu pedido.
        /// </summary>
        internal static string rpc1 {
            get {
                return ResourceManager.GetString("rpc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nunca es mal momento para comer.
        /// </summary>
        internal static string rpc2 {
            get {
                return ResourceManager.GetString("rpc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para llevar?.
        /// </summary>
        internal static string rpc3 {
            get {
                return ResourceManager.GetString("rpc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú:.
        /// </summary>
        internal static string rpc4 {
            get {
                return ResourceManager.GetString("rpc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesa:.
        /// </summary>
        internal static string rpc5 {
            get {
                return ResourceManager.GetString("rpc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva:.
        /// </summary>
        internal static string rpc6 {
            get {
                return ResourceManager.GetString("rpc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string rpc7 {
            get {
                return ResourceManager.GetString("rpc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceder al tramite e imprimir factura.
        /// </summary>
        internal static string rpc8 {
            get {
                return ResourceManager.GetString("rpc8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Pedido.
        /// </summary>
        internal static string rpc9 {
            get {
                return ResourceManager.GetString("rpc9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Reserva.
        /// </summary>
        internal static string rrb1 {
            get {
                return ResourceManager.GetString("rrb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva tanto de portatil como de salas de estudio.
        /// </summary>
        internal static string rrb2 {
            get {
                return ResourceManager.GetString("rrb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portatil?.
        /// </summary>
        internal static string rrb3 {
            get {
                return ResourceManager.GetString("rrb3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva:.
        /// </summary>
        internal static string rrb4 {
            get {
                return ResourceManager.GetString("rrb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Reserva.
        /// </summary>
        internal static string rrb5 {
            get {
                return ResourceManager.GetString("rrb5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu módulo.
        /// </summary>
        internal static string rreu1 {
            get {
                return ResourceManager.GetString("rreu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para acceder a la disponibilidad de los docentes.
        /// </summary>
        internal static string rreu2 {
            get {
                return ResourceManager.GetString("rreu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string rreu3 {
            get {
                return ResourceManager.GetString("rreu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar el formulario.
        /// </summary>
        internal static string rreuf1 {
            get {
                return ResourceManager.GetString("rreuf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para enviar una solicitud para una reunión.
        /// </summary>
        internal static string rreuf2 {
            get {
                return ResourceManager.GetString("rreuf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesor:.
        /// </summary>
        internal static string rreuf3 {
            get {
                return ResourceManager.GetString("rreuf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia Reserva:.
        /// </summary>
        internal static string rreuf4 {
            get {
                return ResourceManager.GetString("rreuf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva:.
        /// </summary>
        internal static string rreuf5 {
            get {
                return ResourceManager.GetString("rreuf5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar solicitud.
        /// </summary>
        internal static string rreuf6 {
            get {
                return ResourceManager.GetString("rreuf6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de tutorias privadas.
        /// </summary>
        internal static string vpr1 {
            get {
                return ResourceManager.GetString("vpr1", resourceCulture);
            }
        }
    }
}
