//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace floridapp.Recurso_lenguaje {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Castellano {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Castellano() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("floridapp.Recurso_lenguaje.Castellano", typeof(Castellano).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscas un portatil?.
        /// </summary>
        internal static string bib_1 {
            get {
                return ResourceManager.GetString("bib_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de reserva de salas y portatiles.
        /// </summary>
        internal static string bib_2 {
            get {
                return ResourceManager.GetString("bib_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofrecemos un sofisticado servicio de reserva de equipos informáticos,   .
        /// </summary>
        internal static string bib_3 {
            get {
                return ResourceManager.GetString("bib_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Reserva.
        /// </summary>
        internal static string bib_4 {
            get {
                return ResourceManager.GetString("bib_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por solamente:.
        /// </summary>
        internal static string caf_1 {
            get {
                return ResourceManager.GetString("caf_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Paella.
        /// </summary>
        internal static string caf_2 {
            get {
                return ResourceManager.GetString("caf_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paella tradicionl valenciana.
        /// </summary>
        internal static string caf_3 {
            get {
                return ResourceManager.GetString("caf_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Paella es probablemente la receta 
        ///más aclamada, popular y conocida de nuestra 
        ///gastronomía. Se trata del plato insignia de toda 
        ///una región, el cual ha permitido que la riqueza 
        ///culinaria española traspase fronteras..
        /// </summary>
        internal static string caf_4 {
            get {
                return ResourceManager.GetString("caf_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Pedido.
        /// </summary>
        internal static string caf_5 {
            get {
                return ResourceManager.GetString("caf_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca.
        /// </summary>
        internal static string f1_bib {
            get {
                return ResourceManager.GetString("f1_bib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cafeteria.
        /// </summary>
        internal static string f1_caf {
            get {
                return ResourceManager.GetString("f1_caf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string f1_ini {
            get {
                return ResourceManager.GetString("f1_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista grados.
        /// </summary>
        internal static string f1_list {
            get {
                return ResourceManager.GetString("f1_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunion.
        /// </summary>
        internal static string f1_reu {
            get {
                return ResourceManager.GetString("f1_reu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salie.
        /// </summary>
        internal static string f1_sal {
            get {
                return ResourceManager.GetString("f1_sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña: .
        /// </summary>
        internal static string lo_con {
            get {
                return ResourceManager.GetString("lo_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo: .
        /// </summary>
        internal static string lo_cor {
            get {
                return ResourceManager.GetString("lo_cor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string lo_ent {
            get {
                return ResourceManager.GetString("lo_ent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string lo_sal {
            get {
                return ResourceManager.GetString("lo_sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablón de noticias.
        /// </summary>
        internal static string new_1 {
            get {
                return ResourceManager.GetString("new_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestras noticias más recientes.
        /// </summary>
        internal static string new_2 {
            get {
                return ResourceManager.GetString("new_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máas noticias.
        /// </summary>
        internal static string new_3 {
            get {
                return ResourceManager.GetString("new_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organizar una reunión.
        /// </summary>
        internal static string reu_1 {
            get {
                return ResourceManager.GetString("reu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con tus profesores de confianza.
        /// </summary>
        internal static string reu_2 {
            get {
                return ResourceManager.GetString("reu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string reu_3 {
            get {
                return ResourceManager.GetString("reu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza la tuya propia.
        /// </summary>
        internal static string reu_4 {
            get {
                return ResourceManager.GetString("reu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza tu pedido.
        /// </summary>
        internal static string rpc_1 {
            get {
                return ResourceManager.GetString("rpc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nunca es mal momento para comer.
        /// </summary>
        internal static string rpc_2 {
            get {
                return ResourceManager.GetString("rpc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para llevar?.
        /// </summary>
        internal static string rpc_3 {
            get {
                return ResourceManager.GetString("rpc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú:.
        /// </summary>
        internal static string rpc_4 {
            get {
                return ResourceManager.GetString("rpc_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mesa:.
        /// </summary>
        internal static string rpc_5 {
            get {
                return ResourceManager.GetString("rpc_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva:.
        /// </summary>
        internal static string rpc_6 {
            get {
                return ResourceManager.GetString("rpc_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string rpc_7 {
            get {
                return ResourceManager.GetString("rpc_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceder al tramite e imprimir factura.
        /// </summary>
        internal static string rpc_8 {
            get {
                return ResourceManager.GetString("rpc_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Pedido.
        /// </summary>
        internal static string rpc_9 {
            get {
                return ResourceManager.GetString("rpc_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Reserva.
        /// </summary>
        internal static string rrb_1 {
            get {
                return ResourceManager.GetString("rrb_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva tanto de portatil como de salas de estudio.
        /// </summary>
        internal static string rrb_2 {
            get {
                return ResourceManager.GetString("rrb_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portatil?.
        /// </summary>
        internal static string rrb_3 {
            get {
                return ResourceManager.GetString("rrb_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva:.
        /// </summary>
        internal static string rrb_4 {
            get {
                return ResourceManager.GetString("rrb_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Reserva.
        /// </summary>
        internal static string rrb_5 {
            get {
                return ResourceManager.GetString("rrb_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona tu módulo.
        /// </summary>
        internal static string rreu_1 {
            get {
                return ResourceManager.GetString("rreu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para acceder a la disponibilidad de los docentes.
        /// </summary>
        internal static string rreu_2 {
            get {
                return ResourceManager.GetString("rreu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string rreu_3 {
            get {
                return ResourceManager.GetString("rreu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar el formulario.
        /// </summary>
        internal static string rreuf_1 {
            get {
                return ResourceManager.GetString("rreuf_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para enviar una solicitud para una reunión.
        /// </summary>
        internal static string rreuf_2 {
            get {
                return ResourceManager.GetString("rreuf_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesor: .
        /// </summary>
        internal static string rreuf_3 {
            get {
                return ResourceManager.GetString("rreuf_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia Reserva:.
        /// </summary>
        internal static string rreuf_4 {
            get {
                return ResourceManager.GetString("rreuf_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora Reserva: .
        /// </summary>
        internal static string rreuf_5 {
            get {
                return ResourceManager.GetString("rreuf_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar solicitud.
        /// </summary>
        internal static string rreuf_6 {
            get {
                return ResourceManager.GetString("rreuf_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de tutorias privadas.
        /// </summary>
        internal static string vpr_1 {
            get {
                return ResourceManager.GetString("vpr_1", resourceCulture);
            }
        }
    }
}
